name: ci

on:
  push:
    branches: [master]

jobs:
  static-test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout website
        uses: actions/checkout@v4
      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: '22'
      - name: run copy test
        run: node tests/test_copy.js
      - name: run layout test
        run: node tests/test_layout.js
      - name: run link test
        run: node tests/test_links.js
      - name: run shim test
        run: node tests/test_shim.js
      - name: run hooks test
        run: node tests/test_hooks.js

  auto-release:
    needs: [static-test]
    uses: openOODA/openOODA/.github/workflows/auto-release.yml@v2.10.44
